
COMPOSER	:= $(shell which composer)
PHP			:= $(shell which php)
PATTERNLAB	:= $(PHP) core/console
WEBPACK		:= node_modules/.bin/webpack
NPM			:= /usr/bin/npm
YARN		:= $(shell which yarn)

STYLES		:= $(shell find source-bundle/*/ -name '*.scss')
JS			:= $(shell find source-bundle/ -name '*.js')
WP_SOURCES	:= \
	$(STYLES) \
	$(JS)
PL_SOURCES	:= \
	vendor/autoload.php \
	$(shell find source/ -type f)

.PHONY: all
all: \
	public/latest-change.txt \
	public/themes/contrib/palm/bundle/palm.js \
	public/themes/contrib/palm/bundle/palm.css \
	export

.PHONY: deps
deps:
	@echo "Composer: '$(COMPOSER)'"
	@echo "PHP:      '$(PHP)'"
	@echo "Yarn:     '$(YARN)'"

.PHONY: watch
watch:
	$(WEBPACK) --watch

.PHONY: clean
clean:
	mkdir -p public export
	cd public && rm -rf css/ images/ js/ bundle/ latest-change.txt patternlab-components/ patterns/ static/ themes/contrib/palm/bundle/
	rm -rf export/*

.PHONY: distclean
distclean: clean
	rm -rf node_modules vendor

public/themes/contrib/palm/bundle/palm.js public/themes/contrib/palm/bundle/palm.css: $(WEBPACK) webpack.config.js source-bundle/style.scss $(WP_SOURCES)
	$(WEBPACK)

.PHONY: export
export: public/latest-change.txt public/themes/contrib/palm/bundle/palm.js public/themes/contrib/palm/bundle/palm.css
	$(PATTERNLAB) --export
	cp -a public/themes/contrib/palm/bundle export/

public/latest-change.txt: $(PL_SOURCES)
	$(PATTERNLAB) --generate

source-bundle/style.scss: Makefile $(STYLES)
	touch $@.new
	echo >> $@.new "// automatically generated by make at $(shell date)"
	echo >> $@.new "// You MUST NOT edit this file"
	find source-bundle/scss -name '*.scss' | LANG=C sort | perl -p -e 's#^source-bundle/(.*)#\@import "$$1";#' >> $@.new
	mv $@.new $@

vendor/autoload.php: composer.json composer.lock
	$(COMPOSER) install || ( rm -f $@; exit 1 )

composer.lock: composer.json
	$(COMPOSER) update || ( rm -f $@; exit 1 )

yarn.lock: package.json
	$(YARN) install
	touch $@

$(WEBPACK): yarn.lock
	$(YARN) install
	touch $@
